version: 2.1
orbs:
  node: circleci/node@x.y
  ruby: circleci/ruby@x.y

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node
    executor: ruby/default
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
  test:
      parallelism: 3
      docker:
        - image: cimg/ruby:2.7-node
        - image: circleci/postgres:9.5-alpine
          environment:
            POSTGRES_USER: circleci-demo-ruby
            POSTGRES_DB: rails_blog_test
            POSTGRES_PASSWORD: ""
      environment:
        BUNDLE_JOBS: "3"
        BUNDLE_RETRY: "3"
        PGHOST: 127.0.0.1
        PGUSER: circleci-demo-ruby
        PGPASSWORD: ""
        RAILS_ENV: test
      steps:
        - checkout
        - ruby/bundle-install
        - node/install-packages:
            pkg-manager: yarn
            cache-key: "yarn.lock"
        - run:
            name: Wait for DB
            command: dockerize -wait tcp://localhost:5432 -timeout 1m
        - run:
            name: Database setup
            command: bundle exec rails db:schema:load --trace
        # Run rspec in parallel
        - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
